apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bi4gy154c-go
  janus-idp.io/tekton: bi4gy154c-go
  backstage.io/kubernetes-id: bi4gy154c-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bi4gy154c-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
