apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bi4gy154c-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bi4gy154c-go 
  name: bi4gy154c-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bi4gy154c-go 
